# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: BUILD_module1
    displayName: Build module1
    type: boolean
    default: true
  - name: BUILD_module2
    displayName: Build module2
    type: boolean
    default: true  
jobs:
  - job: BuildArtifacts
    displayName: Build Artifacts
    steps:
      - checkout: self
        submodules: true

      # Restore Maven Cache BEFORE Running Maven Commands
      - task: Cache@2
        displayName: Restore Maven Cache
        inputs:
          key: maven | "$(Agent.OS)"
          restoreKeys: |
            maven | "$(Agent.OS)" | dependencies
          path: $(Pipeline.Workspace)/.m2/repository    
      # Install Java 17
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'     



